#!/usr/bin/env bash
# making sure nginx can listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
curl -i 0:80
