#!/usr/bin/env bash
#install nginx and redirects to holberton school string
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' | sudo tee /var/www/html/index.html 
sudo nginx -t
sudo service nginx start
