#!/usr/bin/env bash
#install nginx and redirects to holberton school string
sudo apt-get update
sudo apt-get install -y nginx
file1=/usr/share/nginx/html/index.html
sudo bash -c "echo 'Holberton School ftw!' > $file1"
service nginx start
